version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rag_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3456:3456"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=ragapp
    depends_on:
      - mongodb
    networks:
      - rag_network
    volumes:
      - ./chroma_db:/app/chroma_db

networks:
  rag_network:
    driver: bridge

volumes:
  mongodb_data:
